# Generated by Django 5.0 on 2025-11-08 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('email_contract_expiry', models.BooleanField(default=True, verbose_name='Contract Expiry Emails')),
                ('email_payment_due', models.BooleanField(default=True, verbose_name='Payment Due Emails')),
                ('email_maintenance', models.BooleanField(default=True, verbose_name='Maintenance Emails')),
                ('email_document_expiry', models.BooleanField(default=True, verbose_name='Document Expiry Emails')),
                ('email_budget_alert', models.BooleanField(default=True, verbose_name='Budget Alert Emails')),
                ('inapp_enabled', models.BooleanField(default=True, verbose_name='In-App Notifications')),
                ('inapp_contract_expiry', models.BooleanField(default=True, verbose_name='Contract Expiry Notifications')),
                ('inapp_payment_due', models.BooleanField(default=True, verbose_name='Payment Due Notifications')),
                ('inapp_maintenance', models.BooleanField(default=True, verbose_name='Maintenance Notifications')),
                ('inapp_document_expiry', models.BooleanField(default=True, verbose_name='Document Expiry Notifications')),
                ('inapp_budget_alert', models.BooleanField(default=True, verbose_name='Budget Alert Notifications')),
                ('daily_digest', models.BooleanField(default=False, verbose_name='Daily Digest Email')),
                ('weekly_digest', models.BooleanField(default=True, verbose_name='Weekly Digest Email')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Quiet Hours Start')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Quiet Hours End')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='action_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Action Label'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Action URL'),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email Sent At'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_sent_email',
            field=models.BooleanField(default=False, verbose_name='Email Sent'),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional data as JSON', null=True, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Read At'),
        ),
        migrations.AddField(
            model_name='notification',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Schedule notification for future delivery', null=True, verbose_name='Scheduled For'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Link URL'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('contract_expiry', 'Contract Expiry'), ('payment_due', 'Payment Due'), ('maintenance_request', 'Maintenance Request'), ('document_expiry', 'Document Expiry'), ('budget_alert', 'Budget Alert'), ('system', 'System Notification')], default='info', max_length=30, verbose_name='Type'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='core_notifi_user_id_f286cd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='core_notifi_notific_cbfe88_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='core_notifi_priorit_8208cb_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
